# Generated by Django 5.2.5 on 2026-07-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_payment_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("needs_review", "Needs Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
